class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'webmirror'
        self.UnzipMirrorCommand = 'unzipwebmirror'
        self.TarMirrorCommand = 'tarwebmirror'
        self.CancelMirror = 'webcancel'
        self.CancelAllCommand = 'webcancelall'
        self.ListCommand = 'weblist'
        self.StatusCommand = 'webstatus'
        self.AuthorizedUsersCommand = 'webusers'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'webrestart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'webusage'

BotCommands = _BotCommands()
